apiVersion: backupschema.jkops.me/v1
kind: BackupDatabaseSchema
metadata:
  name: db-backup
  namespace: {{ .Values.namespace | quote }}
spec:
  dbHost: {{ .Values.dbSecrets.DB_HOST | quote }} # Replace with your database service name in api-server
  dbUser: {{ .Values.dbSecrets.DB_USER | quote }} # Replace with your DB username
  dbPasswordSecretName: {{ .Release.Name }}-db-secrets
  dbPasswordSecretNamespace: {{ .Values.namespace | quote }}
  dbPasswordSecretKey: "POSTGRES_PASSWORD"
  dbName: {{ .Values.dbSecrets.DB_NAME | quote }} # Replace with your database name
  dbSchema: {{ .Values.dbSecrets.DB_SCHEMA | quote }} # Replace with your schema name if different
  dbPort: {{ .Values.dbSecrets.DB_PORT }} # Default PostgreSQL port
  gcsBucket: "db-backup-schema" # Replace with your GCS bucket name
  kubeServiceAccount: {{ .Release.Name }}-ksa # Operator’s ServiceAccount
  gcpServiceAccount: {{ .Values.gcs.GCS_SERVICE_ACCOUNT | quote }} # Replace with your GCP SA
  backupJobNamespace: {{ .Values.namespace | quote }}
  backupInterval: 59
