apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "db-backup-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "db-backup-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-ksa
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-credentials
      containers:
        - name: operator
          image: karanthakkar09/db-backup-operator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5
      affinity:
        # Pod Affinity (Required): Must run in the same zone as the database pods
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ .Chart.Name }}-postgres  # Matches the DB StatefulSet
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}  # Ensures the same Helm release
            topologyKey: "topology.kubernetes.io/zone"  # Same zone (e.g., us-east1-b)
        # Pod Anti-Affinity (Required): Must not run on the same node as another operator pod
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ .Chart.Name }}  # Matches the operator itself
            topologyKey: "kubernetes.io/hostname"  # Different nodes