apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}