apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-application-secrets
  namespace: {{ .Values.streamlit_llm_namespace }}
type: Opaque
stringData:
  PINECONE_API_KEY: {{ .Values.application.PINECONE_API_KEY | quote }}
  PINECONE_ENVIRONMENT: {{ .Values.application.PINECONE_ENVIRONMENT | quote }}
  PINECONE_INDEX_NAME: {{ .Values.application.PINECONE_INDEX_NAME | quote }}
  GEMINI_API_KEY: {{ .Values.application.GEMINI_API_KEY | quote }}
  GCP_LOCATION: {{ .Values.gcs.GCP_LOCATION | quote }}
  GCP_PROJECT_ID: {{ .Values.gcs.GCP_PROJECT_ID | quote }}
  TOP_K: {{ .Values.application.TOP_K | quote }}
  SIMILARITY_THRESHOLD: {{ .Values.application.SIMILARITY_THRESHOLD | quote }}