apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-application-secrets
  namespace: {{ .Values.streamlit_llm_namespace }}
type: Opaque
stringData:
  MISTRAL_API_KEY: {{ .Values.application.MISTRAL_API_KEY | quote }}
  PINECONE_API_KEY: {{ .Values.application.PINECONE_API_KEY | quote }}
  PINECONE_ENVIRONMENT: {{ .Values.application.PINECONE_ENVIRONMENT | quote }}
  PINECONE_INDEX_NAME: {{ .Values.application.PINECONE_INDEX_NAME | quote }}
  GEMINI_API_KEY: {{ .Values.application.GEMINI_API_KEY | quote }}
  TOP_K: {{ .Values.application.TOP_K | quote }}