# kafka/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-kafka-sa
  namespace: {{ .Values.kafkaNamespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
automountServiceAccountToken: false