appNamespace: ENC[AES256_GCM,data:9KEa2EyFQpWaFQchnJ4=,iv:ndwRi2Qk+f2hJykjykSD9lpOS6BSBbKO2Xauxz9VLnY=,tag:crsvNvGzjcedps+8zqrxpg==,type:str]
dbNamespace: ENC[AES256_GCM,data:R2XmKHHDnoIon3voTQ==,iv:oj3lhv3xEwKMdM5zWbRjOXRJDpBNFmQycUbqeLpUqac=,tag:ZWmDuVV2GRHuA7uN7oIS4g==,type:str]
replicaCount: ENC[AES256_GCM,data:8w==,iv:C5M1tq6DiKRomxYVkoqJevYQdVHnjWXE3WV6z8UcyIs=,tag:CBvYoe2R3ImkGc2535cWmg==,type:int]
image:
    app:
        repository: ENC[AES256_GCM,data:6DJB9ZHNTwzbe9erTYc43O/yKab/LhVGOg==,iv:zZouqt+oAwWPgJSsaegN5BTCOBTWAw6L9A1U7R1MygI=,tag:zXIN+IR99buytfdtRvM3Sw==,type:str]
        tag: ENC[AES256_GCM,data:Qz1PDP8J,iv:yQLklCrhNd6mG4eeHJ3kMN9hN9cQbSL90pzDiBjWNtQ=,tag:2ebjjBV1r7rL2DmMWGf/dQ==,type:str]
        pullPolicy: ENC[AES256_GCM,data:aadHk0ZX,iv:WOLIC1dqT7w49N4oLybdd2et9nr738yM2IHbv+V765w=,tag:If4N58kS/oWA2M2t7kYEIA==,type:str]
    database:
        repository: ENC[AES256_GCM,data:3HxB8Ecvdkp8OtSAGdQENFlIKM4zFFCQJcsJcFaFrXj1,iv:RxnavXovDNi+M79olj3urV7AfyJ2QFurwO9l1miyO4E=,tag:rOrK3n4DH209HYtVIxWHuA==,type:str]
        tag: ENC[AES256_GCM,data:C5T7CfIq,iv:GIo6mwyTK56jOnR2d0C5fFgs7muUHPjUMQVWFo4jblo=,tag:E58wCdNlEDnBkAEPapaUSA==,type:str]
        pullPolicy: ENC[AES256_GCM,data:wtFIx02/,iv:1l9NOfI3jqDxZ6CAm6wmg6W4V6VWbyIDSPfvQHXVlEE=,tag:y0X7Wofv98tQTkDV70KI/g==,type:str]
    postgres:
        repository: ENC[AES256_GCM,data:mV7o11yWFAA=,iv:2/4cECOOAtTjUU9HFYLRzmA1F+vdbwED1+Cputb0Vpo=,tag:0jaeMlca/in3pKMgMQ4lfA==,type:str]
        tag: ENC[AES256_GCM,data:KoY=,iv:Ws4qAhKu+szSma8TD8kp1HacrJbl/OBsGZt+05J4kr4=,tag:X1Pqdro+yObfb/kF0O5vog==,type:str]
        pullPolicy: ENC[AES256_GCM,data:Qp+b6ZG8k+pqAh+K,iv:bg5EpynLDFHmVYhzxQrTwgGeUToaKfov1DCNKONvHyw=,tag:yedlK450628h6hMkZuk3lQ==,type:str]
service:
    type: ENC[AES256_GCM,data:eN4K4CqFk5rYkXsm,iv:j7GTOleiHnCJavKDtD+35MPbdOPm0N9cR46Uf3URsLo=,tag:8shu7AbKLE0eQIxdKDgy2Q==,type:str]
    port: ENC[AES256_GCM,data:d+fK9w==,iv:nRnJEIYvdGc9NnLW/b0wdvr6bA9IQKMBFTF2MxtyI9A=,tag:sBhfyf7ZzPxPRfWT5WTsCw==,type:int]
resources:
    app:
        requests:
            memory: ENC[AES256_GCM,data:IiBCsnE=,iv:u9EXT9G6Yhz+dQmPKNEOQLMB6b4i4PrVdTNp/eKdS/s=,tag:hAG8eLoI+fcgVDRDNOOJBQ==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:RiM3k+k=,iv:wboqNIrYy0pLhhiJodNAHXxQv7a7jZrC7m0NCy4dBcI=,tag:e3U1ftxJPQW27qBzTbgcnA==,type:str]
    postgres:
        requests:
            memory: ENC[AES256_GCM,data:C9e6Hzo=,iv:V3UdV1Y0jMg8WnJbUAM9jC4mvregKwpUba717ECfcmI=,tag:8aLagSec6uXAJWnMfJbm7Q==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:UGvs,iv:gElvN/qR7DrLkkf7IPmmcarJDKAW99ePxnDoaFpL2gE=,tag:Ijol9kBgZfmmkS8MIA1VSg==,type:str]
config:
    app:
        env: ENC[AES256_GCM,data:vTfoTgthGE2J3A==,iv:nNv7Y8nBxV42Amu3yjsFm9lPki4Lnvle3QR52YO7qi8=,tag:1gmzQEw2cN3Ybk1SN5iw9g==,type:str]
        logLevel: ENC[AES256_GCM,data:OMj1GA==,iv:+C6Tx11mVvEHlWxpj0PAmuNamjHJzmYMyHcXNQ/XV9I=,tag:ZVWyFxY+mIRD94sbxa7StA==,type:str]
postgres:
    dbName: ENC[AES256_GCM,data:RCmc,iv:VsMPByI2eKnDNof0BCO3WTcS4tryWdWLtxstT4cXRK4=,tag:EPv8P0/QxwJnDoyTwCCq/g==,type:str]
    dbUser: ENC[AES256_GCM,data:7wrgEqU=,iv:NXh6PwBwLho82f7gp3Isqrs+Fr/ib/Muk/qgITTH8Cw=,tag:yRmZYkqbyN2ZFjJK9wbZlg==,type:str]
    dbschema: ENC[AES256_GCM,data:6dGH,iv:WQbGOl/CUnmgI76UHz6xKd8qvZC4A0nDcTC+0kDvEL8=,tag:GH9tYdbDC2MXlk3Kj086IA==,type:str]
    dbPort: ENC[AES256_GCM,data:F7pfPQ==,iv:Ar8Stc748WsXIAG9sZ7eQbH/yB0oVSJvCXYLytUfmUs=,tag:YdtArr8GKrdS28MGIF+WBg==,type:str]
gcs:
    GCS_BUCKET_NAME: ENC[AES256_GCM,data:A3YnoJB+6SK5S/Q5Pnlzc4ZL5w==,iv:mu/yPCvyvIMjFy+Byj1ciqeAlKJfgCMXay4F+NA7toQ=,tag:vX/TnSIfpv1Ehm7t7Vb4yg==,type:str]
    GCS_SERVICE_ACCOUNT: ENC[AES256_GCM,data:wHsTgGedjKXwO9bBfDIrkrva/x2eukBvUOjHZv3l9eTHjVyI6gD25HWeyUzYw6jNL4zdUangaUJzKHkuh1GM1lK2,iv:ilgNl2c8JWr8MZo97rRPTrPYPBpBw49XuPKHrXdRbR0=,tag:slKsbDKu+LAZwd9O4XEQlQ==,type:str]
secrets:
    postgresPassword: ENC[AES256_GCM,data:0Lk0uu8yUEhFjwAoqoQ=,iv:x3N+jS/MTgmsTsUYkrNNCFEIS77pGj5OvVZj1FCoCtI=,tag:gAMVBLA/jebsMmILoixy9w==,type:str]
docker:
    username: ENC[AES256_GCM,data:jP0tZvW4eqq5JfKZtTw=,iv:gqPDZbsdaEy9aOaVIqt5v18ZpXFy4c0yoUa+iyTMqUQ=,tag:D/9yHFpxql+egA+cvDBxjg==,type:str]
    password: ENC[AES256_GCM,data:shvEDXE5IBA4QahQA+Q=,iv:plUSGwMm2BZsx252Qvm5ORFSJGhJOHwGaTgKUTuyQK4=,tag:MtH1747FRsevG6bLuRNd8Q==,type:str]
    email: ENC[AES256_GCM,data:nxWkm/MEnfbgYqxmPEq/bz9l2oRb6/dnW6CMo1o=,iv:NRY0Ze6F+1ZiCVR8QgpF2GSn7bvZRno2vGYK6ZBWkKg=,tag:WjB4Ja5fTAFCWyrJ4wD0Yw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us-east1/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-03-30T02:12:33Z"
          enc: CiQAkrm5hwaQmelv3JqmUAtCtQG7DMNr2nqCG4pGoJwuIQbaSBYSSQBBsUUVF64JE4+aqxJwol2t+6G26fvOaf8J60YQSM6DXGRgSx7iQjiVdJthsqP4ey6/gI+xFu9bd0Va29LJBcnh6l3W3CiLAXg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-30T02:12:33Z"
    mac: ENC[AES256_GCM,data:rTJmCkoZVYBkID7VT/bDLGUCleelRvrKNJeVlHEJ3DU0SwsHMBJce0CkEFN5kYAhmhx0zqJHw27dtx+zKtvphLXJUIuCJi8GHHiSFt6qzIgPC2HIeFsXDeCOLeWTPP2Rau7bVEBGiNqfF1fUlXvXLep5l7sU33pkcQc+wRgRin8=,iv:uwKgr2MtM3CzZ15hxPNoqJk866UgLkCzxIkkgEmTS/A=,tag:axReXLsTteQ4h9pyBSNNsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
