apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
  namespace: {{ .Values.appNamespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
  namespace: {{ .Values.dbNamespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}