apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-credentials
  namespace: {{ .Values.appNamespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": {{ .Values.docker.username | quote }},
          "password": {{ .Values.docker.password | quote }},
          "email": {{ .Values.docker.email | quote }}
        }
      }
    }