apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-server-pod-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]