apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ksa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: api-server-gcs@silicon-works-449817-n7.iam.gserviceaccount.com