apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: "Helm"
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-postgres
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: postgres
          image: {{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}
          imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.dbUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi