# trace-processor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-config
  namespace: {{ .Values.traceProcessorNamespace }}
  labels:
    {{- include "trace-processor.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrap_servers | quote }}
  KAFKA_GROUP_ID: {{ .Values.kafka.group_id | quote}}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote}}