apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.traceProcessorNamespace }}
  labels:
    {{- include "trace-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "trace-processor.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-ksa
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-credentials
      containers:
      - name: trace-processor
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-kafka-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-kafka-config
              key: KAFKA_GROUP_ID
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-kafka-config
              key: KAFKA_TOPIC
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-application-secrets
              key: MISTRAL_API_KEY
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-application-secrets
              key: PINECONE_API_KEY
        - name: PINECONE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-application-secrets
              key: PINECONE_ENVIRONMENT
        - name: PINECONE_INDEX_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-application-secrets
              key: PINECONE_INDEX_NAME
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"