# trace-processor/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ksa
  namespace: {{ .Values.traceProcessorNamespace }}
  labels:
    {{- include "trace-processor.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcs.GCS_SERVICE_ACCOUNT | quote }}
automountServiceAccountToken: false