apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "test-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "test-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-ksa
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-credentials
      initContainers:
        - name: db-migrate
          image: {{ .Values.image.database.repository }}:{{ .Values.image.database.tag }}
          imagePullPolicy: {{ .Values.image.database.pullPolicy }}
          command: ["flyway", "migrate"]
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgres.{{ .Values.dbNamespace }}.svc.cluster.local:5432/{{ .Values.postgres.dbName }}"
            - name: FLYWAY_USER
              value: {{ .Values.postgres.dbUser | quote }}
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secrets
                  key: POSTGRES_PASSWORD
            - name: FLYWAY_DEFAULT_SCHEMA
              value: {{ .Values.postgres.dbschema | quote }}
            - name: FLYWAY_CREATE_SCHEMAS
              value: "true"
            - name: FLYWAY_CONNECT_RETRIES
              value: "60"
            - name: FLYWAY_VALIDATE_MIGRATION_NAMING
              value: "true"
      containers:
        - name: test-server
          image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgres.{{ .Values.dbNamespace }}.svc.cluster.local
            - name: DB_NAME
              value: {{ .Values.postgres.dbName | quote }}
            - name: DB_PORT
              value: {{ .Values.postgres.dbPort | quote }}
            - name: DB_USER
              value: {{ .Values.postgres.dbUser | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secrets
                  key: POSTGRES_PASSWORD
            - name: GCS_BUCKET_NAME
              value: {{ .Values.gcs.GCS_BUCKET_NAME | quote }}
          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5