# grafana-provisioning-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-config
  namespace: monitoring
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /etc/grafana/provisioning/dashboards