# podmonitoring.yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ .Release.Name }}-postgres-monitoring
  namespace: {{ .Values.dbNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics  
      interval: 30s
      path: /metrics