apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-server-pod-manager-binding
  namespace: {{ .Values.appNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-ksa
  namespace: {{ .Values.appNamespace }}
roleRef:
  kind: Role
  name: test-server-pod-manager
  apiGroup: rbac.authorization.k8s.io