apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.dbNamespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    - port: 9187
      targetPort: 9187
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-collector
  namespace: gmp-system
spec:
  selector:
    app.kubernetes.io/name: collector # Match the pod’s label
  ports:
    - name: prometheus
      port: 19090
      targetPort: 19090
