appNamespace: ENC[AES256_GCM,data:HPMziM4SayNudbNehWA=,iv:ThSW6qO0V+VQlcZl8yY63ExZr1C2tVN5+S78e7Lu1O8=,tag:bQatKQ/e5PA3Uwf7H7kvsw==,type:str]
dbNamespace: ENC[AES256_GCM,data:0OYRhJTz4dMiFevwQQ==,iv:k4R0m4EfZXjzhUIjNx/F/O/KePfDD0oHfylOMv36oi8=,tag:OWCOaH24i73phb3QYUnYFw==,type:str]
replicaCount: ENC[AES256_GCM,data:3Q==,iv:v/EtBhCYFjPwkUcKlb3Z88bOuiSonrL2PWVUdpg3kwY=,tag:ONS4wInjBakTtIxumd6RBg==,type:int]
image:
    app:
        repository: ENC[AES256_GCM,data:msv2zua0N2vJhEn3YapYX/m8HCKf4Uv0Iw==,iv:VirRRIZeI4RmarBPBfnpPsuHix66QYq1LsttYc6qzyE=,tag:IG16rzvbkXmf/rjyMInuTw==,type:str]
        tag: ENC[AES256_GCM,data:DAYjvnmQ,iv:fLYa/yn1g5aMZWp1/lFZP4irn/nO3fnlaM2cIvf5TwE=,tag:OQBP/QHniHnE+xkW8SRTzQ==,type:str]
        pullPolicy: ENC[AES256_GCM,data:xC41IUxL,iv:Tx2UFdvgQVgAVbugs1b4u3TlOmOVb4tkwh1ATW2tFfA=,tag:1DaL0uy4Ta6w/p3bMRHGSw==,type:str]
    database:
        repository: ENC[AES256_GCM,data:cyzr3cQuG5ZcjxtMfT+TEcdsgVcMYXAFP4+0i52gctnQ,iv:cknaaXLzAvXC6j8KnmtlkwWoIp/ObqRe9PAHhUxBKUw=,tag:RMSNdHMWZhoz+aZFj6ArZg==,type:str]
        tag: ENC[AES256_GCM,data:GfUCd/Xs,iv:8ightvJ/nVuzPwoN4rcnCKW8t6r6TUdNzeZVcKVqdDI=,tag:gwpVTKsYmpk3AxaU96dC4w==,type:str]
        pullPolicy: ENC[AES256_GCM,data:InPQuKN6,iv:CM+oKuy07IpFoSvPLMTY9HrCpyNekx0ApMtyHrh806k=,tag:o6OKKzKt78Os5xPKy27gaA==,type:str]
    postgres:
        repository: ENC[AES256_GCM,data:7kll/FYPCT8=,iv:WWYt6F1i3GAC0kjj+A4FzKm8bV8kHmEsRa6sRfbSOvk=,tag:m3YCq13anUMZ1Z8Y6mxcyw==,type:str]
        tag: ENC[AES256_GCM,data:nUg=,iv:5L5vQD0fQYZA9N4byTuqpzvCEwx2ixAe2JWPzJrwYE4=,tag:jG3CzHVnPSE2ONUD/FHhug==,type:str]
        pullPolicy: ENC[AES256_GCM,data:jHFiFSIfChbdXnSJ,iv:BBkCmtMW7NThkDKMvbEh1eWQWLo+1lOdZXdcX7z+0E8=,tag:FQPErrkR5cq3WXCHqBS0bg==,type:str]
service:
    type: ENC[AES256_GCM,data:uzL8m9tyttgJV6vv,iv:nUGOt7R/msRHmoN9Dtfri2jv4pTIE/qLd0Oml2c1/s8=,tag:yHO7lhn0ucYhxMZN327zDg==,type:str]
    port: ENC[AES256_GCM,data:BQDQLw==,iv:0MA2CBL1dJJ7Kz6RLUpNuGHzDFxdfEl9sHDaJeXoJ3Y=,tag:+mO2grAboBkCYFP6MjsHeA==,type:int]
resources:
    app:
        requests:
            memory: ENC[AES256_GCM,data:wAHBwj8=,iv:J9mP1RzGW8QEwLLoc/ORH3P3PT+hnWSH0Nk3lHVFuGc=,tag:z/tLhcKtplYZYwxtdhaLqQ==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:I63B3Fw=,iv:HrZekCXCTQdDc+oX0DJthEVo+aXPqbRaCBI0tFYeMdA=,tag:AWyjY+GDvWu44rAtj6po9g==,type:str]
    postgres:
        requests:
            memory: ENC[AES256_GCM,data:kp7ZrcM=,iv:M5mIcn0VlIFDLB1qml2EyGgf+1QleFKqJODukEFFWTk=,tag:0RImGVU61c22XuTi5wht0A==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:jqf4,iv:htdBMv2OgOJPED+RUl3YJvgcyvME96Ha1rVChTmlbqA=,tag:jqxIjqsx/MLu5uW19+G2fA==,type:str]
config:
    app:
        env: ENC[AES256_GCM,data:v8mHBOrcuM8CjQ==,iv:VdNsRoWEdbNGdY9CIdJhzN2FHFASdhPC3ev+e1OaGUY=,tag:XH4CGZur9ysKLp3K2LC0QQ==,type:str]
        logLevel: ENC[AES256_GCM,data:Wnh/fA==,iv:JRp+M13JXASxlQL6Bh+ADIeQrbB1j9E/ICNIKFOXqWc=,tag:hIdeK6Dn1OHvcBD3Rt3eVA==,type:str]
postgres:
    dbName: ENC[AES256_GCM,data:9t7R,iv:hr/+2yjzhcF6++Kl2FuD5GserV0wx3rUmBwIybW8yZM=,tag:ehc76RZOQMjKBOxbXpLnNA==,type:str]
    dbUser: ENC[AES256_GCM,data:RLKa8aE=,iv:NCJ5gtv3pPiUsll6vHdJ/zzJssDJsovgHmV67UT0kgo=,tag:PplZQaGvrficHLEAiLCk+A==,type:str]
    dbschema: ENC[AES256_GCM,data:uonk,iv:WBA8GbsjXhOHMBYjToTkGYn7udK8tHYvjitWMbnMI2I=,tag:jvFl2W0eCbGpCZ5XnklPUA==,type:str]
    dbPort: ENC[AES256_GCM,data:ycDwCA==,iv:e/mdfUYgKUqBjTfVt/CHxJVIDyv5yrFzPZFfdyJzpd8=,tag:uZmz0fh9YeAKYijFvQjAuA==,type:str]
gcs:
    GCS_BUCKET_NAME: ENC[AES256_GCM,data:/SCMohjJ8y9wCArB6eUsKMioGw==,iv:MEYzJ+l06BJlb37dBAGXTCt0NfVIuDspUCgC7em0SY4=,tag:XTSJdH2r40tLPbGRmCDfYw==,type:str]
    GCS_SERVICE_ACCOUNT: ENC[AES256_GCM,data:4OwdE2dBN5SCY82O0kV8PjrgpakvEg7lgl3JabsjX9t2p6t9TKE4+8NkPY5WJtNsluG9KoBn0g9i1Nw5CS9PRhPN,iv:yYJWulTQxTVh1gH+5wjD0Nr2OlHvefyzizRrs8l13fE=,tag:T/8F5N6T5byBX4SWLqYHFA==,type:str]
secrets:
    postgresPassword: ENC[AES256_GCM,data:VeJRv+HMzcz+7gVZQrs=,iv:Xan3F4fPKS9+nnAUtxGV0e99PtFRLgLyLM6I7GlW0mY=,tag:+/MSAPHj/nCXIrpl6k5TJg==,type:str]
docker:
    username: ENC[AES256_GCM,data:gwa0MmcwLhWH0wXTu1g=,iv:ei0KCXFfchsdG4KIG7V3TMF81sMd4e+CylvQG3XLgpw=,tag:6l9o2d3fLJ0N7aaoXiW3IA==,type:str]
    password: ENC[AES256_GCM,data:4czlg4DULsYd0sEpam4=,iv:imNVdu3ZVQdJhzvdEbHPzufvtyoDJr+hBIfRRCWxoeA=,tag:/+BZxqW6MSoBJzv6Ef14XA==,type:str]
    email: ENC[AES256_GCM,data:01r9nZ42xFPD4ne/AilQpZ6d5OxKX2zz+bRdZyQ=,iv:88JmMOZbSnB9QxZDeYE/pg5qPpNADMKQvSPgFHl+t3o=,tag:siMM13A3+8cjgoAvZe/f4g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us-east1/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-03-28T16:59:37Z"
          enc: CiQAkrm5h7pFlnLZbkPh3jdwq+2LIY0KRcfgrjt6c0LaZ327vEgSSQBBsUUVfSEMC0GBngU6c9mjG9MBtGcu5rLBhgFaQ8Q7z9sST6K6bZzOUUIAgA3LV3DJVX+3zqAK/IiUYx//oHbkhoqABx74g8I=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-28T16:59:37Z"
    mac: ENC[AES256_GCM,data:mbW9+MCn9kUL5+cdLC3/4/7z2cSbqT4AEatgQwmbYNs1LGIit5gTZ6VtMU1pWdxaFOTz5jCIV+IlbA5iKd4gRkLh9ldSM3q+OM7r2KS1Nm3GBZehpzIzwu1RG5BbamHqSLD9i8UgB+UYPDGOkiuCEKpnFYSCO8G60iH1BkaiWKY=,iv:97PbYEJEFGwcTOjELKr7PBf6RYEK6W6/NVi4l+4FrZI=,tag:KAaZ+vhHU12U6c+aH7g60A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
