appNamespace: test-app
dbNamespace: test-db
replicaCount: 1
image:
    app:
        repository: karanthakkar09/api-server
        tag: latest
        pullPolicy: Always
    database:
        repository: karanthakkar09/database-migration
        tag: latest
        pullPolicy: Always
    postgres:
        repository: postgres
        tag: "15"
        pullPolicy: IfNotPresent
service:
    type: LoadBalancer
    port: 3000
resources:
    app:
        requests:
            memory: 256Mi
        limits:
            memory: 512Mi
    postgres:
        requests:
            memory: 512Mi
        limits:
            memory: 1Gi
config:
    app:
        env: production
        logLevel: info
postgres:
    dbName: api
    dbUser: admin
    dbschema: api
    dbPort: "5432"
gcs:
    GCS_BUCKET_NAME: csye7125-trace-data
    GCS_SERVICE_ACCOUNT: dev-api-server-gcs@silicon-works-449817-n7.iam.gserviceaccount.com
secrets:
    postgresPassword: 1163boylstonst
docker:
    username: karanthakkar09
    password: 1163boylstonst
    email: thakkar.kara@northeastern.edu
