#ENC[AES256_GCM,data:c0E6Qf3/2nb86xjUnfLCZHeV,iv:CsYb197c5GnjgnJRGFMBOfb/olF6iMM7OmCxcDj2cD8=,tag:3qT6UiKPI3lMOd5/ZiDu/A==,type:comment]
kafkaNamespace: ENC[AES256_GCM,data:4/AW9jY=,iv:5PgAuHMf2PaAvu+LhyB8SmbyW1X8j97pyNDSaHt0hjo=,tag:xQKKGSrCrLTJD1USQmoSOw==,type:str]
apiServerNamespace: ENC[AES256_GCM,data:LEUzm7Qem0UqLol3M9o=,iv:GezqJpY3W1/fCeK1njsK5RUgmv+z6Yvd6lf+xxipU1I=,tag:HAl5AtFWBv672Z29nyHexA==,type:str]
traceProcessorNamespace: ENC[AES256_GCM,data:1FFWmgGcpQOxoT1zmi2F,iv:V6YzvxQBwKL+zk8wmW4Lc0xANn2RtPhjvlqTm9lBYPg=,tag:rciAWI+SbolWwSlZqvStTw==,type:str]
kafka:
    namespaceOverride: ENC[AES256_GCM,data:oj5K9JQ=,iv:3r/11mg6GmnYaKasgMX0rWH6sLJxYJytiEUkwJCacX4=,tag:jRNkBRKRl638bX9Dx7Q7aw==,type:str]
    broker:
        replicaCount: ENC[AES256_GCM,data:fA==,iv:qWWzKMCky+IGj8aGmD5DMEXr9HYV4LJNzXNgsZFBl90=,tag:82Qll11c7khV/kycLXMLNg==,type:int]
        roles:
            - ENC[AES256_GCM,data:vHqYKtZ7,iv:ZtkpZvNHyfbvnBUWbMWGzBzm8WiezGY5GywqZV87Z/s=,tag:ENGMSkbw296zGjeuibrjnA==,type:str]
    controller:
        replicaCount: ENC[AES256_GCM,data:EQ==,iv:3u/g1vXswNVPBcGYcyUcK32eZP8GkNpuVPnT49Xkxr0=,tag:qF9dH9VtTlX1MK4YVVKjwg==,type:int]
    kraft:
        enabled: ENC[AES256_GCM,data:HnuarHo=,iv:rHsbuag6X4MYBQAYZJy2z2+3xULZ6qDYI+cHNQI+owM=,tag:pqQ5E0ZdOy5IG1en6ecTCg==,type:bool]
    resources:
        limits:
            cpu: ENC[AES256_GCM,data:30Slkg==,iv:fWO7dnHrVxmbomZZUptopb0+Ba53tafbANjEJKa4YqY=,tag:oQcoqWENH32e9WbBKDptNA==,type:str]
            memory: ENC[AES256_GCM,data:OlyBYPI=,iv:Gp9CLZ/p5bfDocqG7O/8iCAd93e2t/Z8nSY6CVlyhlg=,tag:4IQ47XhjJ768qB7msE1AXQ==,type:str]
        requests:
            cpu: ENC[AES256_GCM,data:VdqTTg==,iv:Fqo8kGoKEd3dOVUlhkW/gIuWvOr2bJKVCnRduRNGUA4=,tag:enyROjN1rCDysmA/mTykiw==,type:str]
            memory: ENC[AES256_GCM,data:hGj07TA=,iv:IW6gRM+YkO1VsvtfDBopDLN3Ti1+Ssg8nO+Qxbm5rOE=,tag:Qxy8xZmTOhsooVv3THcw3A==,type:str]
    persistence:
        enabled: ENC[AES256_GCM,data:/CkEvQ==,iv:d/NDdcBJ4+UeENC/TMdvJF+3xsJAHd10miI9jH/vycQ=,tag:RbEya114otEd2Umqd9insQ==,type:bool]
        size: ENC[AES256_GCM,data:EdGk,iv:5D9nENOuBV73+TVljdEKGCdRbGj2SLnnez8aQI5a0a0=,tag:smfKeywcqi9pKWkK07sEkw==,type:str]
    zookeeper:
        enabled: ENC[AES256_GCM,data:uF5yXQ==,iv:x2SmtnhwBOo6/mCY9sO4uxvNQe1+fOdAwO41ev/0k8w=,tag:7E68QUNTYe4WFdvgCTPoug==,type:bool]
        replicaCount: ENC[AES256_GCM,data:og==,iv:8Ks/pBx/gw9tnPd92JjSnXcCsjQYFTakMjsobODyFl0=,tag:KwWhoO+IVDaKEummf4nYmA==,type:int]
        #ENC[AES256_GCM,data:ozdz1JKAPeWDFmOOqzi6gNJETeZQ7Rxi9HqYLpGFprfb0rw5DxqtFVXv,iv:qVO156HoDr5r1tvEXZM7TXAorT0Lvgj6sBjOqF8oLsI=,tag:XKIKBh37LUqaftQ+Z8WwzA==,type:comment]
        namespaceOverride: ENC[AES256_GCM,data:dE3LfWg=,iv:yvXDtUxKn9SzafM3lYyfgzfdelWpxO11EjEPJgtR0TQ=,tag:qluIqMYYG8Q9eZHQuXoM7Q==,type:str]
        resources:
            limits:
                cpu: ENC[AES256_GCM,data:Q4q5bQ==,iv:vCqAlfTFgQmruCy8yhIfUC/FDQ4+LnwnmSrwOlZCtLA=,tag:6bhT4VPRPY81oA78WxsPaw==,type:str]
                memory: ENC[AES256_GCM,data:T3OfaDI=,iv:lro8VrO/mzTGikaxKSj3drGaijM0yvOTkYXKKqInnjs=,tag:qiy6hpTVEnkts83Me89VDw==,type:str]
            requests:
                cpu: ENC[AES256_GCM,data:xvF0Ww==,iv:urW0Z+ycmkUQtNStmqTf5AWXBk6Z8LT4WdlDQpduXys=,tag:pzWAisU22FwvJf9bvRVjwg==,type:str]
                memory: ENC[AES256_GCM,data:B28VOgo=,iv:DFzLRwGMQM8xQCY/9Oa0b09P/BEuyV5dmwTHw4n6av4=,tag:1rZO1tdFIDOV/FuaoMO05A==,type:str]
        persistence:
            enabled: ENC[AES256_GCM,data:egFeeA==,iv:ESbmiCWRvh4f7zbBqrcmSrry9zlyM6JNcgVbiM6WOEE=,tag:qyACltaMXCXTVZhUZH4GSg==,type:bool]
            size: ENC[AES256_GCM,data:qBvX,iv:R/rx+ENyO4KL98S3mqXXQp6AIMgW7PGf1V40wZOiNT8=,tag:3ZkpDYwUHAEH69/I1wFUpA==,type:str]
    service:
        type: ENC[AES256_GCM,data:hmayirQreMMs,iv:xi7jL5aRiAp7KXpa+ufKUJhrt1qTLVqO4pm91t5HuKw=,tag:reXJ2NoCytq+qerz8IIiEA==,type:str]
        port: ENC[AES256_GCM,data:auE5Jg==,iv:DEiPhRByMqqwaxYtoT/XQM0wYuOLkdIokUawzbBKMfQ=,tag:3RH7oRNBeLqhRXs1U6PauA==,type:int]
    auth:
        clientProtocol: ENC[AES256_GCM,data:SLAY56Il9YfI,iv:gKKEOAszkoiKW8UwplSB/zphzsPw5UFOuiscUhpayyw=,tag:4ieTvvxxtIWbW7jIyFgv9w==,type:str]
        interBrokerProtocol: ENC[AES256_GCM,data:qHaxLG+8Oxpl,iv:ANKWrenfZ22GdJcQlEywX9M6pPbxyAD7cx0kSVOJYdQ=,tag:0ArgnNQz71fN6kRB+sH7Rw==,type:str]
        sasl:
            enabled: ENC[AES256_GCM,data:4gaX1Tg=,iv:vNjP0EgKeWb4SSnaXtid6jX8R+f8V2apqFi/LWASug8=,tag:nPzNRHwnpf8CpUGUQO10sA==,type:bool]
    listeners:
        client:
            protocol: ENC[AES256_GCM,data:dXMo5hITqP+Z,iv:uJR2R5qzfKOOZPH5Y1YJp/98vFwO2T9pmYyBsOGg8Uo=,tag:76bkoK+5jkjvKqkqzLEddg==,type:str]
            name: ENC[AES256_GCM,data:B2f+Fu7B,iv:QQrgVnNBPvrONZRLu2VaKxvftyaz4UhY074AXKMoNa4=,tag:wqs9Wfr9TKCYxSF2UVsl3g==,type:str]
            port: ENC[AES256_GCM,data:32K3lg==,iv:HadB/ERukxMtEnwrnDO3BNWeC2umlAv1K+Du0YktWqs=,tag:ZbHxr7Sa/tKduAZsuKOVWw==,type:int]
        interbroker:
            protocol: ENC[AES256_GCM,data:5Vs5RGx4tOJn,iv:BVLjxzUNqOXncQmRfxDlwF4dQWd1av89nFhYJDvbEEU=,tag:RxutSyEbI8YXVBfgdRa3SA==,type:str]
            name: ENC[AES256_GCM,data:aOpIvTlbuUQ=,iv:PbbNwbEvLImHmsIn7BtILkARbghjuN4XrfzMUol+7F8=,tag:UcLUjRf+/LBtSbVJZ+69fA==,type:str]
            port: ENC[AES256_GCM,data:E7dANg==,iv:F/P5uCr0SJvBKLwGNY/lEHdProlpJgFzgs9Rp0CmBBw=,tag:UFRtfQXeEXMFBXY/xl86bw==,type:int]
    advertisedListeners:
        client: ENC[AES256_GCM,data:Aw5StWBCgn4GQeu+gCA2n+IqhWMZJnJN0O5NPGksb1Yjc6p4ZE21NJhNaLk1,iv:q5Tp0HY1JLAZe6SBywoxIZR8EkJAmuBCIgs5TWtT6RA=,tag:cauat+2qAniShft9Nht4XQ==,type:str]
        interbroker: ENC[AES256_GCM,data:97k/Xw31oDwyr3EEbkqpaVVnkrfhtTUDEjZxAflhFaeUmIp7DF7KrVo2jEZnFU0+KuWbRBgzAIyvEf9VnMfUNgX6jZeFu+oTaGj2YDezwOVQaqV1Cwsu,iv:BrHY08gHELhB+YNHXVsfEiXJHdqTZPhFcmx4UGeAmbo=,tag:95zmBkKToAjBrq927/UfwA==,type:str]
    externalAccess:
        enabled: ENC[AES256_GCM,data:i2IAXDc=,iv:N2yBYNUcJLWi6tnEopACh/3eBbkjucC7glx3t+9Llpg=,tag:YDWl0zczdMlafvWDSC0sVg==,type:bool]
    offsetsTopicReplicationFactor: ENC[AES256_GCM,data:JQ==,iv:7tLbmxwNkHgNJGw2YFOcs1Q0FZ7BsjxPZzukJcSadtE=,tag:rt/Lp0XnMEcWFO4Jelm5OQ==,type:int]
    extraConfig: ENC[AES256_GCM,data:IoAMaLW2WqXH4EzDAMT7oepIUC0QFXMcEXu73PVYu9VhjpEAD1ZLJdrkU3igupTZPS9R+mxvsqEqEMmivMSA1ct1f4fsEbaNJ+MLH4y5/HHUrYB2OwNwADIm+pnaCACCvnQKlgjtSStC9A==,iv:iv6hL/qH4GKZucS0HXPevb0yXrIZGJL7txKSFV/fJ8k=,tag:PQHk6DY7gFTdHox8FvcyjA==,type:str]
    livenessProbe:
        initialDelaySeconds: ENC[AES256_GCM,data:2Ok=,iv:CB/2/35wcoLOZTlcpCA7T20+m4UDWD5M5IpBauAfEjU=,tag:kT2dDbgGCVGNMdvDti9qbw==,type:int]
        periodSeconds: ENC[AES256_GCM,data:9Oc=,iv:K7YYN9tdjr2GmDuXQCYKnpFLDOxGkhRDiYqp2pMhTYE=,tag:yWVmWKdI12f/JMQ9BscQ4w==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:rg==,iv:p5cZMEjX5b6hw0mfSRMfH5iube8USt6TMiqTGTgq5XE=,tag:n9J96+SpYOK2WWNo7D/UVA==,type:int]
        failureThreshold: ENC[AES256_GCM,data:Fg==,iv:DRAQPj4y6CfLsvlIY/d6XTMSedDCIS6ZAjC2u3LXpdc=,tag:rVie5mCImiAaBbXZAHge3g==,type:int]
        successThreshold: ENC[AES256_GCM,data:pw==,iv:FEo8lIJz7vbw7L6bJjchHWgZzQuwDqRlVMDtRa2yfaQ=,tag:5zYwTLsZQYOIFPUoiAVvyg==,type:int]
    readinessProbe:
        initialDelaySeconds: ENC[AES256_GCM,data:JhM=,iv:pE/ljqxAlOY0cVBdMCZtKHB4yG1yHv34XxnD4F69gTw=,tag:fl9GRAeVUvuQ3135Pw0VUQ==,type:int]
        periodSeconds: ENC[AES256_GCM,data:Yhg=,iv:nFJFlruei9QJ5XQ9ctBRDFl7cLQmvXODP1bias1HATg=,tag:+WUep9XFFXXdCckswQsSgQ==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:eA==,iv:7+A3M29VShN4EiLAcKQChFP95S6m0Cj4a7fDm0jdAN4=,tag:0FT97uXQssWLSrXc4eJoiw==,type:int]
        failureThreshold: ENC[AES256_GCM,data:Ww==,iv:5XKu9OfigognkL4nE8PXGOkFAjaHzMFa1l9X2mX/WtA=,tag:tHCCZwS1/Kr97Fn5x6IKZg==,type:int]
        successThreshold: ENC[AES256_GCM,data:SA==,iv:bFTQUkvy9PG61w68L/so/NldE/tSUsnt3LFZNyKihHk=,tag:/Ylf7Jh+hZCUaSc5E+M6lw==,type:int]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us-east1/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-04-14T07:05:26Z"
          enc: CiQAkrm5hy3rif9JiW7P/LoE57wc+rD4GMrNgqMVBwzavVz9fBMSSQBBsUUVU9PAXGhaIyqZb3tj+7pVUEfN8ghVxj55KiDC/cD+5Ks4iZThdNcQRS0bE6sD9kElyZk8Up/nq2x91IUK+udqNT4I6m8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-14T07:05:26Z"
    mac: ENC[AES256_GCM,data:P6KRpB4lwK1jmgxCOG6iYP1S6LhjorjzxLTA64OVFSHsULBkmLV61Adav8KaSqaPpZbsIDgFZcW2HIajwDP542lXqi0DKeo5/EtRQVHwBlBpuSqTgoVp1Y3Q40Fj2z+lEqcwnabnJSZkp5Px5B2JDwgbMHqRz/fIeDmhDknPFNo=,iv:gOm+X5efpfgkvRz1d0McXyTn09qZF5ZuMAu0As3LQWY=,tag:0L/wvCqZDPxMYx9huCqXyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
