#ENC[AES256_GCM,data:kh2vYbO/q0SEl+HCt3TBGsu+,iv:Vx+8P2dBX9xnZn2hRGW0QDSZ0fSyRiWLyeISgBIo4tI=,tag:hbDiSOF1iVEwm8O0S+MAtA==,type:comment]
kafkaNamespace: ENC[AES256_GCM,data:+UGjWPY=,iv:LFf4QOUNVePmLl2YBqxDw9EhYHoPs6Xnu+aFSO0D0KU=,tag:9br5yivVvtG3bP2636QTkQ==,type:str]
apiServerNamespace: ENC[AES256_GCM,data:63xi/lH3dsIHyMxTvJs=,iv:XczxFzUQKKziw7OctThYvjRBYutNzcvSOHajhtuLIA4=,tag:aT/fZOaNx1sCswVDGMS1Jw==,type:str]
kafka:
    namespaceOverride: ENC[AES256_GCM,data:GHP08pE=,iv:TjXkbtf4OwTdFprjFh7sw+sdv9pYZzfHSW3vPLn+EPw=,tag:wn2OTOYMi+eGy8jMYKIqpw==,type:str]
    broker:
        replicaCount: ENC[AES256_GCM,data:Bg==,iv:kPe2Z/WQMkjd687mxd6rPOnHdpG2srI4DNprWlL4C+o=,tag:sYgKnS3fd1Dx7jpsUpAN1A==,type:int]
        roles:
            - ENC[AES256_GCM,data:BGu7G963,iv:YudUvGhBiB5jn8p3gPpgTLTivQeDUDveMM3jzigWPMA=,tag:OjTgPbae0q37Dkht2vr1ug==,type:str]
    controller:
        replicaCount: ENC[AES256_GCM,data:2A==,iv:iT0jhtQAVYJjQrh46BlKYAosR8PykblKTNab6YLy680=,tag:DbbM9rhl8/1v5MqEJ0g3Lw==,type:int]
    kraft:
        enabled: ENC[AES256_GCM,data:+/gdV58=,iv:GK5J4YEH9Bdksc2k9Iv5cMKzOq+SxaQdf5mcmbJ51Q4=,tag:XLpQplbgmHaPZFxxlSmFXg==,type:bool]
    resources:
        limits:
            cpu: ENC[AES256_GCM,data:fiPFzg==,iv:ajwaI9O2k8zopMLqnzgcfa5Nasg0g1Vp7M1oxKrufxg=,tag:4coQqROhz0ssvCYwD26DBw==,type:str]
            memory: ENC[AES256_GCM,data:8MC24G0=,iv:6eXXMjL7S+pREDzrfvLvfEBn9Nc064Xy1neRxr1qLhA=,tag:zKtp5oKaT3DltocbNAb3nA==,type:str]
        requests:
            cpu: ENC[AES256_GCM,data:QA41qQ==,iv:BH+4L4laLUqQCPOEpuVf+zDs7YxWNTReuFpfb+A6Hs0=,tag:znT4/IcuU8upuHm0pwzZTQ==,type:str]
            memory: ENC[AES256_GCM,data:a97cFPw=,iv:G/QA1X9wwy9RtyQIsEL715KQo6FCUB9WK99kQGPxLb4=,tag:1x03z2vx4wEqM5mbnfy5Mg==,type:str]
    persistence:
        enabled: ENC[AES256_GCM,data:Nm9oKQ==,iv:AB+Nq9M8H6e/v7SoifCqST/ENaLTIuXWBpefzRaFO3c=,tag:cTvfzMAlCJ64gyUSaAuHmQ==,type:bool]
        size: ENC[AES256_GCM,data:lG3v,iv:UrmwtjUV6fudScguiu6MVQGkQ6wKOKXgyCA64YMWYT4=,tag:X6uBpUn5J5pfrwl9Z/SG/w==,type:str]
    zookeeper:
        enabled: ENC[AES256_GCM,data:d0r9Zg==,iv:ymhOWCcnLsYKyGVnBoDVjrx0pCwL9Fr74bpdZRis0wg=,tag:RK+6Vnt1EFqo6xF9ZaCPtg==,type:bool]
        replicaCount: ENC[AES256_GCM,data:jw==,iv:vyHONLvyfK7Y6lN6LidC7LKEj6/1TrMJlHncODSkv6Y=,tag:PZiv+2RCcUhwMd2Qmn1EYw==,type:int]
        #ENC[AES256_GCM,data:WRfbTS38IRbz4ljRJMeZ6LSNKCa304QfE7U24Au0G9Ez1rL1OnDoHc8e,iv:qZw6EVF7TYmwhygZdTT8W796B+GFiHv6rJK+pmF7yqE=,tag:Nqnkmx9LtNY0Sw3PXnFwDg==,type:comment]
        namespaceOverride: ENC[AES256_GCM,data:+TlUgi8=,iv:xfJmPrmC1h2k5gPsJ+I3bkF2WuddCI7hzimt7LItrc0=,tag:omnnEHFTUVjs5gnefb6RKw==,type:str]
        resources:
            limits:
                cpu: ENC[AES256_GCM,data:7Gu7Jg==,iv:Sw+RLTMRwK/GgyWlW3oM3mtS1aJR3MzcVsKONtnhILc=,tag:zpCdf90fJ9DeHHbZBNPtgw==,type:str]
                memory: ENC[AES256_GCM,data:h8jpOQs=,iv:OMTW0dXvPvBb0uxdYMwNHYIU8F39meX70vC3TXacaLw=,tag:FktAXQ5eCH0BsteVtaKB0Q==,type:str]
            requests:
                cpu: ENC[AES256_GCM,data:3za07g==,iv:XOgp0Y7peR5HmmglDgiv13uRF5QcZ+5FnQJELZKC9A0=,tag:KpBeiPmIpftrtvC9cIhrTA==,type:str]
                memory: ENC[AES256_GCM,data:efUQnU0=,iv:0/z/ms4dtQlbuogC3DquTAw0kJRUWTqSYOyulDWRJ+c=,tag:QsL1FZPcxOmZevPWbzNUUA==,type:str]
        persistence:
            enabled: ENC[AES256_GCM,data:tfRrvw==,iv:LnvdpQLUwY6kKnnMjyK6KRnwyYtgBUVYbWAoYnMtwQE=,tag:S/yDX72ojTTwayob4JH/fw==,type:bool]
            size: ENC[AES256_GCM,data:/HD7,iv:iydAv2hmruYbC4qQW1+AUhXp8cFsJwXCclEa7bvj/hY=,tag:CsKgyf/9ksHiZw1NSoTJwQ==,type:str]
    service:
        type: ENC[AES256_GCM,data:7nlbPa2lkVaQ,iv:/utM2ueMnPT/SGt9KAO6cM2q6M8EiimNxLkBcjqODQg=,tag:BW4YFFRZI+ccN4sDQ4k3cg==,type:str]
        port: ENC[AES256_GCM,data:RxABiQ==,iv:S6zNl/l7kEUHN+mXkjHeu+A7cFjmUPpllclMzXjA+ig=,tag:08fU6QId/hfV7HSgO2h6yg==,type:int]
    auth:
        clientProtocol: ENC[AES256_GCM,data:tIkmS3MAhBZr,iv:axbihXGOdTB8oBMSUPTZvquS2r170Nv3wz/i38SWHeU=,tag:Izhu+E2Vl622eCCM6eiWEw==,type:str]
        interBrokerProtocol: ENC[AES256_GCM,data:V67yntdDHMMs,iv:iILU94yu9IEFMD8yrAWl80pPJNkhWpaKsn7JtWBKW7E=,tag:V81exq7AN3ymRXtJvT3t7Q==,type:str]
        sasl:
            enabled: ENC[AES256_GCM,data:CkikB4c=,iv:shK4H1QQ0n9ZHSTYvfxUzvu8BlRMksBcsn6fW9mzJRI=,tag:4r13JU4DeeO2tbd6E5egNA==,type:bool]
    listeners:
        client:
            protocol: ENC[AES256_GCM,data:0sGtvIaDETRN,iv:5osDSdexSZyMEwgu2nvGAOBd0QpdORTx95HxnZ09Hrg=,tag:aZJsdvMRMUNEwEGEj47Y1w==,type:str]
            name: ENC[AES256_GCM,data:UyFwoNfU,iv:1/JXBGeAS8MYs3X/lAWm0I7wQweKvvBs06yQugQrd9Y=,tag:I1ckNfPtHwv7TSMn2tD3Gw==,type:str]
            port: ENC[AES256_GCM,data:Y8IQvA==,iv:SkNvjFqu6YLBCtsUcl0LTwCt3GkFaUsY9PA0k2mjFGA=,tag:wQt4A9QOrjig+v+ihKOkQg==,type:int]
        interbroker:
            protocol: ENC[AES256_GCM,data:9bSdUgJsHX2M,iv:bJ/ReLsFJ29Mkr/Q7PRDWpDegS8H0/gV5SKInZeDPFI=,tag:JdIMilppmvij5d4Aa+YD0A==,type:str]
            name: ENC[AES256_GCM,data:GE97fw/6tFU=,iv:FfIK+AoFiBt9s/a6UWbvSt+W3VasAsWZzi6zKpOVSkE=,tag:PfjMAzdlauZy0h64TEsa2Q==,type:str]
            port: ENC[AES256_GCM,data:6zg79A==,iv:YIGCpXH9f9f1Cr0v2daICfdv7fBe+AAKrf9dDpyGd54=,tag:V0XN8mlzrrLxkkvrR8zSow==,type:int]
    advertisedListeners:
        client: ENC[AES256_GCM,data:82I6AApbtgphBU5v7RkMq3Chv32ys5Pcp0n6X9OnzIkj3cfwvwsgE6+DNiJVsg==,iv:HD6l1GGHKsNcT0rq8rkF6cg/0A2sauCCF42Mc5rKOsk=,tag:mHV+rwy4O9PytMh2xlgvKA==,type:str]
        interbroker: ENC[AES256_GCM,data:29otCDm/kivdLF/BNQM7VwDLwoiwkTIVRt9JJtG1SJMv8wFX/5v6ZHSrfoAanjc4TKAX9Jhk/dE0Jp3UyCx2hH6s0J2PGkZ53kHzbRLCrV4K1PtCi+dP,iv:cwHbgxkZEbKW9y4uK4rMODrqG1LjN0bdBj/DumAJMNQ=,tag:ZVgMgZrWCKVjP/ahRAF27w==,type:str]
    externalAccess:
        enabled: ENC[AES256_GCM,data:rm78+mw=,iv:7OHVWuM5gsJtWPXcpPC6HEksB2HCTcj4hvVOjEiH0tM=,tag:9/RPh6Lu/XYbzqow7tZAwQ==,type:bool]
    offsetsTopicReplicationFactor: ENC[AES256_GCM,data:Aw==,iv:2UkNesNx/3y/ehjoPJlUMbQema3AYGChXG3JWAZKFUE=,tag:7ihSnvf6uqRLCtVy6/Cn9g==,type:int]
    extraConfig: ENC[AES256_GCM,data:C/sBfo7vs1Q+DyV72Nro161zMMmTWL4ROez7bKomflukLpoWWZ4p0yP/zWFL3qK5JiEaZhNtcpkzzQGqC7s43iglwOtv0264JiHqUWaS80Y0EZyBKB3NW13OVRroogNAUiMygmn6DnLXww==,iv:24qWz4VrR235EDZrIHQ8bF3G3j1leDfx+ASr2M0BbPg=,tag:+AiDxPhrD6sgx67ddF2jdw==,type:str]
    livenessProbe:
        initialDelaySeconds: ENC[AES256_GCM,data:484=,iv:8z3W0VDDv/hKi13wlUTFPAO6habOGDuVYS8PUhGfHcs=,tag:swSlFwgOXUxJWYrxoL0usA==,type:int]
        periodSeconds: ENC[AES256_GCM,data:zrs=,iv:uAG5vJ4G/wEY9+A00UkHmL7xfKi++I1vV+LOuOMT7h0=,tag:dSZ39eaNRsLgqpOQ/WZUMA==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:zA==,iv:nbd78UeRWl22vaSiR37OwRIVWRkiZ4kInnzlKNQgAB8=,tag:MpjL8bndo6/xbxClS9YpCQ==,type:int]
        failureThreshold: ENC[AES256_GCM,data:QA==,iv:oMwPwV1kMSeVWZwvBCiDSuZq3tbdQhjyzYKFPmI8Ijk=,tag:PwvRrWbybBi4h7Bpevg00g==,type:int]
        successThreshold: ENC[AES256_GCM,data:8A==,iv:+qxHU/0GZyKTol4jDfUWfMme0pGrlP9BRjVhfpU2P78=,tag:+4+hEuK/M9x255+yY9Rvhw==,type:int]
    readinessProbe:
        initialDelaySeconds: ENC[AES256_GCM,data:Jio=,iv:hxZr/Ys5RCGiVW4Jq+pk+cxdfaizbBKhnsfBxV752W4=,tag:E8yRU15lY0ydCTFL4gyAyw==,type:int]
        periodSeconds: ENC[AES256_GCM,data:4R8=,iv:DKEYXjHfjhMCR0ByW7s2rJMvwvDaD8Auq7EjmWE/1NU=,tag:CpXfBnsXrJQUU2ow4vO9PA==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:xw==,iv:5uzaJuMqv4B70Y9nz7ouBxMsM1AsW2KuKYU3T+CgJEY=,tag:QN9ucSbWcv70342rJHelfQ==,type:int]
        failureThreshold: ENC[AES256_GCM,data:nA==,iv:GpJ/ungD6Ym2Uk+4JkaT55fDHI95j7LASGvJ5pI8RWQ=,tag:D6da+uN+RdpoijiNlblcuw==,type:int]
        successThreshold: ENC[AES256_GCM,data:cA==,iv:NusOS018gAVCQV+G4L3iIWuoMBGWG63ldZt3Bu8j8ew=,tag:kPzPnmH8uRIIvxK73KFxXw==,type:int]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us-east1/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-04-14T00:04:29Z"
          enc: CiQAkrm5h6xr3SYTVRxHIoWzdC9m4B7QDQP+Jvbi8rCLisOUSnYSSQBBsUUVxgcs9k2NP0ffgTqUP1sRB6ueY7tgmrt/IbOwxSVvHbjbE0XLv2qQBgb+IW3jzzN6e3a9GZaZWFZzXo7PlrATLN3vkn8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-14T00:04:30Z"
    mac: ENC[AES256_GCM,data:zeoVzfnKmmeRKgOuh5g+lCWxsAe6xHmD2/E5dhFNWFlmwvI3jTBd2bG2UhlfCQT4csR0klVPBtzQG+RH+86Kcr6R5IE9DK990H7YazdXV0O9J09h9Y3AgjNcAC48gWUue+9kc9/OLcg9AUaus0vgKl021B8eEzOdY9+A7KkFU3g=,iv:QqgtM81JpPDtKX03I9XzvZ7YSvIaS94Xg4a45lwxvIU=,tag:+qQiEaT+WM+A3/Im5ONypQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
