namespace: ENC[AES256_GCM,data:hlGhcrIxMTOvlrJqtZ54RDgu,iv:XrUkJuhxc6sW2U544xMLF4GUaea66yu2VZl0uplN4VQ=,tag:3A97JYcLFEaoANcoWXviGQ==,type:str]
dbNamespace: ENC[AES256_GCM,data:E0AuP9ITvaQ6HR6c1g==,iv:iZWyORHuMRkUrDlaz2Z9NC1r5hIl+AWP14NhplC7Ejw=,tag:gl8anKUG+IXppDjuTnWQ3w==,type:str]
gcs:
    GCS_BUCKET_NAME: ENC[AES256_GCM,data:RmxLhhlC0gbSQ9ugilsF0QfINg==,iv:eZYi/QH6efHhw4qqLv0xhkC2JsGV7ZmwjOiAL6VKIQ4=,tag:Pb3+Y9VcBUz4WWxrmLa/Xg==,type:str]
    GCS_SERVICE_ACCOUNT: ENC[AES256_GCM,data:Q7Oghedz96rP4+HhZ0+h83tEpZKKhDYm/XIVWv70xHwRkaOEfLHzpLTpL90k+F7HkWUqOloYXVoEtmzRLBdF3ItH,iv:7daJDaWf5/yty5JhV4pCJn/dWz9LYJzulP6PdU2I4AA=,tag:Coc9WhhjDA35ZcWCDTDU7Q==,type:str]
secrets:
    postgresPassword: ENC[AES256_GCM,data:dWiy5+GlMcf8m6PEFS0=,iv:sQTj97BPnB53SrfpymxyZTMy3NBUSpJE9vbpwIIT3H4=,tag:+DCh3nOhb+JP/RD+UA17sQ==,type:str]
dbSecrets:
    DB_HOST: ENC[AES256_GCM,data:EAIZ/UPAb6Wah60MPLvPYgS9pJlrrleMVYnwj9qENyz0IaBm5I0KGordxYYcY8k6f+oj,iv:LdyIABJNGs7LG6QiC+EUzc+XXwN1DyJ/+4+eQsrPdKw=,tag:+ltq3wEGi9w8y1EU0oiF/w==,type:str]
    DB_USER: ENC[AES256_GCM,data:PsYbSO8=,iv:TQOl6qNoJ6G+5t5iEguRswn5ayW5R0vdPmPULj0m3P4=,tag:PatdkD2kWYW+wEShRlE5Bg==,type:str]
    DB_SCHEMA: ENC[AES256_GCM,data:J5ck,iv:KJt/Jxo98C6G7ZsRkciNU+zykrU9cr2NIBsOD4TnTjc=,tag:6jH/8NGwlK77yKwFrLam3g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:mRuz0Q==,iv:/kPFHDxH+VtcJ4oEOyUdSxiMFGvU3IXVakGpkk1Obao=,tag:jT7MwaQ/BooAOjE6/X3Y6w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:hPJv,iv:UU1Fhlqj0bC8rSa0Jh+leIUpgQwsnANnaiUSASHxErM=,tag:JmE/gCl2FP32DfpsjWEMSw==,type:str]
docker:
    username: ENC[AES256_GCM,data:ddtVJusHZBfAWUR3peY=,iv:iUa8yANJzIVvwZkPSQQo1TmxrXyiBV16s+/2Q9pNGCE=,tag:KgFq24g/XfZQp+es6oTqig==,type:str]
    password: ENC[AES256_GCM,data:GWMdJIRBc9p48LGoRyY=,iv:/5hNLDzLSOBalEt4E4myTDGpESCQxjCHsACeoLY5NtQ=,tag:scl4kpNUMSHkQIQdMf4Waw==,type:str]
    email: ENC[AES256_GCM,data:ryiiLaK79OCTyIjz94LtbrS4Ji84KLBl/8xnpL4=,iv:IIQyAPzfyS5drvePnsb4VG8fN0c73wISjBU4Qe4h3eA=,tag:jkfvhrHLmVV6w+ngraxUOQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us-east1/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-03-28T16:34:17Z"
          enc: CiQAkrm5h84KNGFhtxTRdCHGb0TfMvucNbBeB22xLfoOWpZxxO4SSQBBsUUVVellGOv+Cb/g3vh5z1jLMO54F0jVqx0HUzN9AGMX814W99l0uD7ubeUtHFVims5Hxnq1b6KwzfuxgARex4Y8O7YAxI0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-28T16:34:18Z"
    mac: ENC[AES256_GCM,data:P5ktSo+/lbWVnSklZwf1pcK4IWGieY4R8Pzjeiuxp32zJ0VlzYJTXijlx8aRCqmWiSi1ghffcszOiLlndNnklTlIyayU6oyBYKf6fiCQvqPiiO6D+o4JM2oXghBTm/nIzU3FHthGo5KADQaHW8ESeceFkd9gDXhXeKFc3zM4Cxk=,iv:UNCN1lgvNetRZSYJA3/Zp20ZDPxJthjWeKXUaC4LFK4=,tag:/macL3Uo3SGUTqAFF1CqCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
