apiVersion: v1
kind: Secret
metadata:
    name: api-server-secrets
    namespace: api-server
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:17Wl86aWCX71YFX2Jy8=,iv:EgriJz9h3mOv3Ibp0upKYR+CKIaxHAjVwGqy6aBR7FU=,tag:09ufLwIo5nkgmxYM5WTEMg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us-east1/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-03-21T00:13:53Z"
          enc: CiQAkrm5hyO3lH9kcuLPNcNeQkVeo22sRHQGeJ8Ab6wycFTff6sSSQBBsUUVlc+CR4r4WMCV7TNfvFV+bTD4E63aQCMYftlAhe/dgUwpm5LW38a7GQAvc+5VagfVJHC0rJoaDhEcLOEnqVF8QbWDxYk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-21T00:13:54Z"
    mac: ENC[AES256_GCM,data:3OF4B4n7Xo6F49qQyCAU8cyM/axeznoScxH7Z5+mR3iXlJ4icQrNLPqykm8655FTsAvpUzj9tGAprPpNfOEH07OPWK88hVS5X3ahfN5Ept9Di0X4pPp3D091S15Q+0khRMgJgoGrKFuvcdybFNssuCD3WXfeyCM9NTrOMXeHzas=,iv:JYeXxyh+301sehnN7XMmdxkXvDGpb1BbyxU5FBPQoL8=,tag:ZzC+/NAKc/BnHoigSljeSg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
